import { SiteHeader } from "../components/site-header";
import { ProjectCard } from "../components/project-card";
import { ArrowIcon, PlayIcon, SparkIcon } from "../components/icons";
import { pricingPlans, projects } from "./content";

function SectionLabel({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }

function ScrollIndicator() { return <div className="relative h-24 w-24 text-[#9d9a96]" aria-label="Scroll to see our work"><svg className="scroll-ring absolute inset-0 h-full w-full" viewBox="0 0 100 100"><defs><path id="circle-path" d="M50,50 m-36,0 a36,36 0 1,1 72,0 a36,36 0 1,1 -72,0" /></defs><text><textPath href="#circle-path">SCROLL TO SEE OUR WORK · SCROLL TO SEE OUR WORK · </textPath></text></svg><span className="scroll-arrow absolute inset-0 flex items-center justify-center text-xl">↓</span></div>; }

function ServiceCard({ title, text, icon }: { title: string; text: string; icon: React.ReactNode }) { return <article className="service-card flex min-h-[210px] flex-col justify-between border border-white/[.06] bg-[#121212] p-5 sm:p-6"><div className="service-icon flex h-9 w-9 items-center justify-center rounded-full border border-white/15 text-[#b65a70]">{icon}</div><div><h3 className="max-w-[170px] text-[18px] leading-[1.02] tracking-[-.04em] text-white">{title}</h3><p className="mt-3 max-w-[250px] text-[11px] leading-[1.45] text-[#85827f]">{text}</p></div></article>; }

export default function Home() { return <main className="site-shell grain">
  <section id="studio" className="hero-glow relative flex min-h-[680px] flex-col justify-between px-5 pb-10 pt-28 sm:min-h-[780px] sm:px-8 sm:pb-14 sm:pt-36"><SiteHeader /><div className="grid grid-cols-1 gap-10 md:grid-cols-[1fr_4fr_1.35fr] md:items-start"><div className="eyebrow max-w-[80px]">AI advertising<br />studio</div><h1 className="text-[clamp(52px,9.1vw,116px)] font-light leading-[.79] tracking-[-.085em] text-white">WE CREATE<br />VIRAL PRODUCT<br /><span className="display-serif tracking-[-.06em]">ADS</span></h1><p className="max-w-[220px] self-end text-[12px] leading-[1.45] text-[#aaa7a3] md:pb-2">Premium AI-generated Instagram ads for ecommerce brands that need to stop the scroll, elevate their products and launch content faster.</p></div><div className="absolute right-6 top-32 text-white sm:right-10 sm:top-36"><ArrowIcon className="h-8 w-8" /></div><div className="flex items-end justify-between border-t border-white/[.07] pt-6"><p className="eyebrow max-w-[170px]">AI visuals.<br />Motion design.<br />Product storytelling.</p><ScrollIndicator /></div></section>

  <section id="services" className="border-t border-white/[.07] px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-12 md:grid-cols-[1.1fr_2.9fr]"><div className="flex flex-col justify-between"><div><SectionLabel>01 / Services</SectionLabel><h2 className="mt-6 text-[clamp(48px,7vw,88px)] font-light leading-[.85] tracking-[-.08em] text-white">WHAT<br />WE DO</h2></div><p className="eyebrow mt-12 max-w-[110px] text-[#e2dfda]">Ads built<br />to move</p></div><div className="grid gap-px bg-white/[.07] sm:grid-cols-2">{[["Viral Product Ads", "Scroll-stopping product videos designed for Reels, Stories, and paid social campaigns."], ["Premium AI Visuals", "High-end product scenes generated around your brand, packaging, materials, and visual identity."], ["Motion-First Creative", "Camera movement, speed ramps, transitions, type, effects, and cinematic product reveals."], ["Fast Production", "Launch new ad concepts without traditional shoots, large crews, studios, or production drag."], ["Multiple Variations", "Different hooks, visual directions, formats, and campaign variations to test what performs best."], ["Ecommerce Focused", "Creative built around product desirability, brand perception, retention, and conversion."]].map(([title, text], i) => <ServiceCard key={title} title={title} text={text} icon={i % 2 ? <SparkIcon /> : <PlayIcon />} />)}</div></div></section>

  <section id="work" className="border-t border-white/[.07] px-5 py-20 sm:px-8 sm:py-28"><div className="mb-12 flex items-end justify-between"><div><SectionLabel>02 / Selected work</SectionLabel><h2 className="mt-5 text-[clamp(48px,7vw,88px)] font-light leading-[.86] tracking-[-.08em] text-white">SELECTED<br /><span className="display-serif">WORK</span></h2></div><p className="eyebrow hidden max-w-[150px] text-right sm:block">Product films<br />made for the<br />attention economy</p></div><div className="grid gap-4"><ProjectCard project={projects[0]} className="aspect-[1.85/1]" /><div className="grid gap-4 md:grid-cols-2"><ProjectCard project={projects[1]} className="aspect-[1.08/1]" /><ProjectCard project={projects[2]} className="aspect-[1.08/1]" /></div><div className="grid gap-4 md:grid-cols-2"><ProjectCard project={projects[3]} className="aspect-[1.08/1]" /><ProjectCard project={projects[4]} className="aspect-[1.08/1]" /></div></div></section>

  <section id="process" className="border-t border-white/[.07] px-5 py-20 sm:px-8 sm:py-28"><div className="grid gap-12 md:grid-cols-[1.1fr_2.9fr]"><div><SectionLabel>03 / Process</SectionLabel><h2 className="mt-6 text-[clamp(48px,7vw,82px)] font-light leading-[.84] tracking-[-.08em] text-white">FROM<br />PRODUCT<br /><span className="display-serif">TO CAMPAIGN</span></h2></div><div className="grid border-l border-t border-white/[.12] sm:grid-cols-2">{[["01", "Creative Direction", "We define the product angle, audience, references, campaign mood, and visual identity."], ["02", "Concepts", "We develop multiple hooks, scenes, visual treatments, and motion directions."], ["03", "Production", "We generate, refine, animate, edit, and polish each creative."], ["04", "Delivery", "You receive platform-ready vertical ads, organized and ready to publish or test."]].map(([number, title, text]) => <article key={number} className="min-h-[230px] border-b border-r border-white/[.12] p-5 sm:p-7"><p className="display-serif text-4xl text-[#d34667]">{number}</p><h3 className="mt-14 text-[18px] tracking-[-.04em] text-white">{title}</h3><p className="mt-3 text-[11px] leading-[1.5] text-[#85827f]">{text}</p></article>)}</div></div></section>

  <section id="pricing" className="border-t border-white/[.07] px-5 py-20 sm:px-8 sm:py-28"><div className="mb-12 flex flex-col justify-between gap-8 md:flex-row md:items-end"><div><SectionLabel>04 / Monthly creative plans</SectionLabel><h2 className="mt-6 max-w-[700px] text-[clamp(48px,7vw,86px)] font-light leading-[.84] tracking-[-.08em] text-white">MONTHLY<br /><span className="display-serif">CREATIVE PLANS</span></h2></div><p className="max-w-[230px] text-[12px] leading-[1.45] text-[#aaa7a3]">Consistent premium content without the cost and complexity of traditional production.</p></div><div className="grid gap-3 lg:grid-cols-3">{pricingPlans.map((plan) => <article key={plan.name} className={`price-card relative flex flex-col border p-6 ${plan.featured ? "border-[#b64460] bg-[#171215]" : "border-white/[.1] bg-[#111]"}`}>{plan.featured && <span className="absolute right-5 top-5 eyebrow text-[#df6b83]">Most popular</span>}<div className="flex items-center gap-3"><p className="eyebrow">{plan.name}</p><span className={`inline-flex items-center rounded-full border px-2.5 py-0.5 font-mono text-[9px] uppercase leading-none tracking-[.08em] ${plan.discount === "Standard rate" ? "border-white/15 bg-white/5 text-[#85827f]" : "border-[#d34667]/40 bg-[#d34667]/10 text-[#df6b83]"}`}>{plan.discount}</span></div><h3 className="mt-8 text-3xl tracking-[-.07em] text-white">{plan.volume}</h3><p className="mt-4 min-h-[38px] text-[12px] leading-[1.45] text-[#aaa7a3]">{plan.description}</p><div className="mt-7 border-t border-white/[.1] pt-5"><p className="font-mono text-xl text-white">{plan.price}</p><p className="mt-2 font-mono text-[10px] uppercase tracking-[.06em] text-[#d34667]">{plan.perVideo}</p></div><ul className="mt-7 space-y-3 border-t border-white/[.1] pt-6">{plan.features.map((feature) => <li key={feature} className="flex gap-3 text-[11px] text-[#b1aeaa]"><span className="text-[#d34667]">+</span>{feature}</li>)}</ul><a href="#contact" className="mt-8 flex items-center justify-between border border-white/20 px-4 py-3 text-[11px] uppercase tracking-[.08em] transition-colors hover:border-white hover:bg-white hover:text-black">{plan.cta}<ArrowIcon className="h-4 w-4" /></a></article>)}</div><p className="mt-8 text-[11px] text-[#85827f]">Need a custom volume, launch campaign, or one-off project? <a href="#contact" className="text-white underline underline-offset-4">Contact us</a> for a tailored production plan.</p></section>

  <section className="border-t border-white/[.07] px-5 py-20 sm:px-8 sm:py-24"><div className="grid gap-12 md:grid-cols-[1.1fr_2.9fr]"><div><SectionLabel>05 / The signal</SectionLabel><h2 className="mt-6 text-[clamp(48px,7vw,78px)] font-light leading-[.84] tracking-[-.08em] text-white">CREATIVE<br />THAT <span className="display-serif">PERFORMS</span></h2></div><div className="grid gap-px bg-white/[.1] sm:grid-cols-2"><div className="bg-[#111] p-6"><p className="eyebrow text-[#d34667]">The advantage</p><p className="mt-12 text-2xl leading-[1.05] tracking-[-.06em] text-white">Faster creative production.<br />More variations to test.<br />Less production overhead.</p></div><div className="bg-[#111] p-6"><blockquote className="mt-5 text-[17px] leading-[1.2] tracking-[-.04em] text-white">“Vanta helped us turn a single product into an entire month of premium creative.”</blockquote><p className="eyebrow mt-10">— Ecommerce founder</p></div><div className="bg-[#111] p-6 sm:col-span-2"><blockquote className="max-w-[570px] text-[17px] leading-[1.2] tracking-[-.04em] text-white">“The final videos looked like a full production campaign without the traditional production process.”</blockquote><p className="eyebrow mt-8">— Brand director</p></div></div></div></section>

  <section id="contact" className="hero-glow border-t border-white/[.07] px-5 py-24 sm:px-8 sm:py-36"><div className="flex flex-col justify-between gap-14 md:flex-row"><div><SectionLabel>06 / Start a project</SectionLabel><h2 className="mt-7 text-[clamp(54px,8.5vw,105px)] font-light leading-[.8] tracking-[-.09em] text-white">LET’S MAKE<br />YOUR PRODUCT<br /><span className="display-serif">IMPOSSIBLE<br />TO IGNORE</span></h2></div><div className="flex max-w-[225px] flex-col justify-end"><p className="text-[13px] leading-[1.45] text-[#aaa7a3]">Tell us about your brand, product, and campaign. We’ll turn it into premium visual content built for attention.</p><a href="mailto:hello@vanta.studio" className="mt-8 inline-flex w-fit items-center gap-4 border-b border-white/30 pb-3 text-[12px] uppercase tracking-[.1em] transition-colors hover:border-[#d34667] hover:text-[#d34667]">Start a project <ArrowIcon className="h-4 w-4" /></a><a href="#work" className="mt-5 text-[11px] text-[#85827f] underline underline-offset-4">View our work</a><p className="mt-16 font-mono text-[11px] text-white">hello@vanta.studio</p></div></div></section>

  <footer className="border-t border-white/[.07] px-5 py-7 sm:px-8"><div className="flex flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><div><p className="font-mono text-[12px] tracking-[.16em] text-white">VANTA AI STUDIO</p><p className="eyebrow mt-3">Vanta AI St. / Buenos Aires / Available worldwide</p></div><div className="flex flex-wrap gap-x-5 gap-y-3 text-[10px] uppercase tracking-[.08em] text-[#85827f]"><a href="https://www.instagram.com/vanta.ia" target="_blank" rel="noopener noreferrer" className="hover:text-white">Instagram</a></div><p className="eyebrow sm:text-right">© {new Date().getFullYear()} Vanta AI Studio</p></div></footer>
  </main>; }
